webapp:
  name: nfl-api
  group: nfl-api
  fqdn: nfl-api.nickknows.net
  path: /
  replicaCount: 1
  container: 
    image: docker.io/ncging/nfl-api:2026-02-23.22.27
    imagePullPolicy: Always
    port: 8000