webapp:
  name: nfl-api
  group: nfl-api
  fqdn: nfl-api.nickknows.net
  path: /
  replicaCount: 1
  container:
    image: docker.io/ncging/nfl-api:2026-08-04.02.35
    imagePullPolicy: Always
    port: 8000
    memoryLimit: "1Gi"
    memoryRequest: "256Mi"
    cpuLimit: "1"
    cpuRequest: "100m"
    env:
      - name: ANTHROPIC_API_KEY
        secretName: nfl-api-secrets
        secretKey: ANTHROPIC_API_KEY
      - name: PGUSER
        secretName: nfl-api-db-app-user
        secretKey: username
      - name: PGPASSWORD
        secretName: nfl-api-db-app-user
        secretKey: password
      - name: DATABASE_URL
        value: "postgresql+psycopg2://$(PGUSER):$(PGPASSWORD)@nfl-api-db-rw.nfl-api.svc.cluster.local:5432/nfl-api-db"
  secrets:
    path: nfl-api
    anthropicKeyProperty: anthropic_api_key
    targetSecret: nfl-api-secrets

db:
  appUserSecret: nfl-api-db-app-user
